# Generated by Django 5.1.3 on 2025-01-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_delete_bottomwear_delete_laptop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
