# Generated by Django 5.1.3 on 2025-01-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
