# Generated by Django 5.1.3 on 2025-01-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
